.TH man 1 "12 Jan 2015" "1.3" "Maker Man Page"

.SH NAME
maker - creates a Makefile and a .h file for C code files.

.SH SYNOPSIS
maker [BIN NAME] [OPTIONS]...

.SH DESCRIPTION
Maker will help you to create a Makefile and includes very quickly, especially for big projects. This command will look recursively from your current repository and find all the C files, which will be added to the sources of the Makefile to be compiled.
.PP 
It will also create an include directory containing a 'my.h' file with the prototypes of every function found in the C files. If any other .h file if found in 'include' file, all will be included in the 'my.h', so you wont have to include them anymore on your others C files. Moreover, it will look for a libmy.a library and link it if found.
.PP
-update	       Looks for an update, and downloads it.
.PP
--install-man    Installs this manual entry.
.PP
-help            Displays help.
.PP
-l               Allow you to add extra lib links to the Makefile. Usage becomes [BIN] -l [LIB]
.PP
                 It is VERY important to add al the libs you want in ONE SINGLE string with spaces between each lib, or next arguments will be ignored.

.SH RETURN VALUES
-1 : on update, if the network appears to be not reachable, the program will print an error and exit.
.PP
-1 : if not enought rights are given to the bash file, commands will probably fail, and errors will be printed.
.PP
-1 : if the name matches with the pattern *.c, it is considered as an invalid binary name to avoid any make problems.
.PP
-2 : if no C files are encountered, a warning is displayed and the program exits.
.PP
 0 : if all went normally.

.SH BUGS
Some particulars prototypes sometimes do not match with the pattern given. Report bugs if so.

.SH AUTHOR
Brought to you by veyrie_f, special thanks to agor_m.

.SH COPYRIGHTS
This is an Open Source project, feel free to change and redistribute it, as long as you quote it's creator. Also feel free to report bugs, misbehaviours, or any other problem encountered at fernand.veyrier@epitech.eu. Any comment is welcome.
